name: Deploy to environment

on:
  push:
    branches:
      - main

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-22.04
    outputs:
      github_repository_lc: ${{ steps.var.outputs.github_repository_lc }}
    steps:
      - id: var
        run: |
          GITHUB_REPOSITORY=${{ github.repository }}
          echo "github_repository_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  build-and-push-image:
    name: Build and push to GHCR
    runs-on: ubuntu-22.04
    needs: set-env
    environment: development
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: GitHub Container Registry login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/${{ needs.set-env.outputs.github_repository_lc }}:latest
          push: true
          cache-from: type=gha
